mushroomcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('mushrooms/', views.mushrooms_index, name='index'),
    path('mushrooms/<int:mushroom_id>', views.mushroom_detail, name='detail'),
    path('mushrooms/create/', views.MushroomCreate.as_view(), name='mushrooms_create'),
    path('mushrooms/<int:pk>/update/', views.MushroomUpdate.as_view(), name='mushrooms_update'),
    path('mushrooms/<int:pk>/delete/', views.MushroomDelete.as_view(), name='mushrooms_delete'),
    path('mushrooms/<int:mushroom_id>/add_shroom_hunt/', views.add_shroom_hunt, name='add_shroom_hunt'),
    path('mushrooms/<int:mushroom_id>/assoc_park/<int:park_id>/', views.assoc_park, name='assoc_park'),
    path('mushrooms/<int:mushroom_id>/unassoc_park/<int:park_id>/', views.unassoc_park, name='unassoc_park'),

]

mushroomcollector/mushroomcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

mushroomcollector/main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Park(models.Model):
  name = models.CharField(max_length=50)
  state = models.CharField(max_length=2)

  def __str__(self):
    return f"{self.name}, {self.state}"

  def get_absolute_url(self):
    return reverse('parks_detail', kwargs={'pk': self.id})
class Mushroom(models.Model):
    name = models.CharField(max_length=100)
    scientific_name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    season = models.CharField(max_length=100)
    edibility = models.CharField(max_length=100)
    parks = models.ManyToManyField(Park)

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('detail', kwargs={'mushroom_id': self.id})


RAIN = (
    ('U', 'Unknown'),
    ('C', 'Currently raining'),
    ('H', 'Rained within last 24 hrs'),
    ('W', 'Rained within last week'),
    ('N', 'No recent rain'),
)

class Shroom_Hunt(models.Model):
    date = models.DateField('date of trip')
    location = models.CharField(max_length=100)
    recent_rain = models.CharField(
        max_length=1,
        choices=RAIN,
        default=RAIN[0][0]
    )

    mushroom = models.ForeignKey(Mushroom, on_delete=models.CASCADE)

    def __str__(self):
        # this method will gives us the friendly meal choices value, so like Breakfast instead of B
        return f"{self.location} on {self.date}; recent rain: {self.get_recent_rain_display()}"

    class Meta:
	    ordering = ['-date']

mushroomcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Shroom_Hunt


class Shroom_HuntForm(ModelForm):
    class Meta:
        model = Shroom_Hunt
        fields = ['date', 'location', 'recent_rain']

mushroomcollector/main_app/views.py
from django.shortcuts import render, redirect

#import CreateView class
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.
from django.http import HttpResponse
from .models import Mushroom, Park
from .forms import Shroom_HuntForm

class MushroomCreate(CreateView):
    model = Mushroom
    fields = '__all__' #this is two underscores
class MushroomUpdate(UpdateView):
    model = Mushroom
    fields = ['name', 'scientific_name', 'description', 'season', 'edibility']

class MushroomDelete(DeleteView):
    model = Mushroom
    success_url = '/mushrooms/' 

def home(request):
    return HttpResponse('<h1>Mushroom Collector Home Page</h1>')

def about(request):
    return render(request, 'about.html')

def mushrooms_index(request):
    mushrooms = Mushroom.objects.all()
    return render(request, 'mushrooms/index.html', {'mushrooms': mushrooms}) 

def mushroom_detail(request, mushroom_id):
    mushroom = Mushroom.objects.get(id=mushroom_id)
    #get parks the mushroom is not associated with
    parks_mushroom_doesnt_have = Park.objects.exclude(id__in = mushroom.parks.all().values_list('id'))
    shroom_hunt_form = Shroom_HuntForm()
    return render(request, 'mushrooms/detail.html', {'mushroom': mushroom, 'shroom_hunt_form': shroom_hunt_form, 'parks': parks_mushroom_doesnt_have})

def add_shroom_hunt(request, mushroom_id):

    # create a ModelForm instance using data in request
    form = Shroom_HuntForm(request.POST)
    # validate
    if form.is_valid():
        # do some stuff
        #creates instance of feeding to be put in database
        #lets not save it yet, commit=False, bc we didnt add foreign key
        new_shroom_hunt = form.save(commit=False)
        new_shroom_hunt.mushroom_id = mushroom_id
        new_shroom_hunt.save() #adds shroom hunt to database, asociated with same id as arg to function mushroom_id

    return redirect('detail', mushroom_id=mushroom_id)

def assoc_park(request, mushroom_id, park_id):
    Mushroom.objects.get(id=mushroom_id).parks.add(park_id)
    return redirect('detail', mushroom_id=mushroom_id)

def unassoc_park(request, mushroom_id, park_id):
    Mushroom.objects.get(id=mushroom_id).parks.remove(park_id)
    return redirect('detail', mushroom_id=mushroom_id)

mushroomcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the 🍄 Collector</h1>
    <hr />
    <p>The Mushroom Collector goes near and far to find and identify all types of mushrooms!</p>
  </body>
</html>

{% endblock %}

mushroomcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Mushroom Collector 🍄</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body class="blue-grey lighten-5">
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper teal">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;MushroomCollector🍄</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'index' %}">View All Mushrooms</a></li>
          <li><a href="{% url 'mushrooms_create' %}">Add A Mushroom</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer teal">
    <div class="right">All Rights Reserved, &copy; 2019 Mushroom Collector &nbsp;</div>
  </footer>
</body>
</html>

mushroomcollector/main_app/templates/main_app/mushroom_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<h1>Delete Mushroom</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'detail' mushroom.id %}">Cancel</a>
</form>
	
{% endblock content %}

mushroomcollector/main_app/templates/main_app/mushroom_form.html
{% extends 'base.html' %}


{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Mushroom</h1>
{% endif %}
<!-- Leaving the action blank will use the same url that was used in order to get the form -->
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="submit!" class="btn" />
    </form>
{% endblock content %}
    

mushroomcollector/main_app/templates/mushrooms/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Mushroom Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content purple teal lighten-4">
                <span class="card-title">{{ mushroom.name }}</span>
                <p>name: {{ mushroom.name }}</p>
                <p>scientific_name: {{ mushroom.scientific_name }}</p>
                <p>Description: {{ mushroom.description }}</p>
                <p>season: {{ mushroom.season }}</p>
                <p>edibility: {{ mushroom.edibility }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'mushrooms_update' mushroom.id %}">Edit</a>
                <a href="{% url 'mushrooms_delete' mushroom.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form method="post" action="{% url 'add_shroom_hunt' mushroom.id %}">
            {% csrf_token %}
            {{ shroom_hunt_form.as_p }}
            <input type="submit" class="btn" value="Add Shroom Hunt Details">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Location</th>
                    <th>Recent Rain?</th>
                </tr>
            </thead>
            <tbody>
                {% for shroom_hunt in mushroom.shroom_hunt_set.all %}
                <tr>
                    <td>{{shroom_hunt.date}}</td>
                    <td>{{shroom_hunt.location}}</td>
                    <td>{{shroom_hunt.get_recent_rain_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ mushroom.name }}'s Park Sitings</h3>
    {% if mushroom.parks.count %}
      {% for park in mushroom.parks.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ park.name }}, {{ park.state }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_park' mushroom.id park.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Parks :(</h5>
    {% endif %}
  </div>
  <!-- Available parks will come after this line -->
  <div class="col s6">
    <h3>Available Parks</h3>
    {% if parks.count %}
      {% for park in parks.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ park.name }}, {{ park.state }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_park' mushroom.id park.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{mushroom.name}} Already Has All Parks Available</h5>
    {% endif %}
  </div>
</div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })

    const selectEl = document.getElementById('id_recent_rain')
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

mushroomcollector/main_app/templates/mushrooms/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Mushroom List</h1>

{% for mushroom in mushrooms %}
  <div class="card">
    <div class="card-content purple teal lighten-4">
      <span class="card-title">{{ mushroom.name }}</span>
      <p>name: {{ mushroom.name }}</p>
      <p>scientific-name: {{ mushroom.scientific_name }}</p>
      <p>Description: {{ mushroom.description }}</p>
      <p>season: {{ mushroom.season }}</p>
      <p>edibility: {{ mushroom.edibility }}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}